services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_api_db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    deploy:
      resources:
        limits:
          cpus: "0.80"
          memory: "250MB"
    ports:
      - "5432:5432"
    healthcheck:
      # Garante que o init.sql terminou de rodar antes de marcar como 'healthy'
      test: [ "CMD-SHELL", "psql -U postgres -d postgres_api_db -c 'SELECT 1 FROM accounts LIMIT 1'" ]
      interval: "5s"
      timeout: "5s"
      retries: "10"
      start_period: "10s" # Dá 10s para o postgres iniciar antes de checar

  app1:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: app1
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres_api_db
      PG_MAX: 30
      HOSTNAME: app1
    expose:
      - "3001"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"
    restart: unless-stopped

  app2:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: app2
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_DATABASE: postgres_api_db
      PG_MAX: 30
      HOSTNAME: app2
    expose:
      - "3002"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"
    restart: unless-stopped

volumes:
  pgdata: