[package]
name = "rust_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "macros", "json"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["fmt","env-filter"] }
anyhow = "1.0.100"
thiserror = "2.0.17"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false